version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build test image
          command: |
            docker-compose -f docker-compose.test.yml build
      - run:
          name: Run all checks
          command: |
            docker-compose -f docker-compose.test.yml up --exit-code-from test
